name = "personal-finance-tracker"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.upload]
format = "directory"

# Environment variables (add your own as needed)
# [vars]
# PUBLIC_API_URL = "https://api.example.com"
